name: pnpm build
on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
    - name: 切换到代码仓库
      uses: actions/checkout@v3
    - name: 设置 Node.js 环境
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: 安装 pnpm
      run: npm install -g pnpm@9.15.1
    - name: 安装依赖
      run: pnpm install 
    - name: lint
      run: pnpm lint
    - name: build
      run: pnpm build